[green_agent]
name = "codewalk-eval-agent"
agentbeats_id = "019c1526-b309-7e81-91a4-fca26b2091aa"
#env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO" }
env = { ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}", LOG_LEVEL = "INFO" }
#image = "codewalk-eval-agent:latest"

[[participants]]
name = "codewalk-qa-agent"
agentbeats_id = "019c152e-544b-7013-9155-2b783a7c7c13"
#env = { QA_API_KEY = "${GOOGLE_API_KEY}", QA_DATA_DIR = "data", QA_MODEL = "gemini-2.5-flash" }
env = { QA_API_KEY = "${ANTHROPIC_API_KEY}", QA_DATA_DIR = "data", QA_MODEL = "claude-sonnet-4-5" }
#image = "codewalk-qa-agent:latest"

[config]
#question = "How does request processing work in FastAPI?"
question = "Explain the role of Pydantic in FastAPI. How does the framework leverage it beyond simple data validation?"
repo_url = "https://github.com/tiangolo/fastapi"
#judge_model = "gemini-2.5-flash"
judge_model = "claude-sonnet-4-5"
