[green_agent]
name = "videoindex-eval-agent"
agentbeats_id = "019c17da-027d-7112-a5ff-f133587888d0"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", EVAL_DATA_DIR = "data", LOG_LEVEL = "INFO" }
#env = { ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}", EVAL_DATA_DIR = "data", LOG_LEVEL = "INFO" }
#image = "videoindex-eval-agent:latest"

[[participants]]
name = "videoindex-qa-agent"
agentbeats_id = "019c17e9-3404-78d3-849e-2c228f932bb2"
env = { QA_DATA_DIR = "data", LOG_LEVEL = "INFO" }
#image = "videoindex-qa-agent:latest"

[config]
question = "Why was Penny upset after Sheldon said 120 for her?"
judge_model = "gemini-2.5-flash"
#judge_model = "claude-sonnet-4-5"
